language: node_js
node_js:
  - 8
  - 6
  - 4
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run test -- --coverage
after_script:
  - greenkeeper-lockfile-upload
  - 'cat ./coverage/lcov.info | coveralls'
cache:
  yarn: true
